<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="homepage_tests.TestConvertEpochToDatetime-20240310224636" tests="1" file="homepage_tests.py" time="0.004" timestamp="2024-03-10T22:46:36" failures="1" errors="0" skipped="0">
	<testcase classname="homepage_tests.TestConvertEpochToDatetime" name="test_convert_epoch_to_datetime_valid" time="0.004" timestamp="2024-03-10T22:46:36">
		<failure type="AssertionError" message="False is not true"><![CDATA[Traceback (most recent call last):
  File "C:\Python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python39\lib\unittest\case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "C:\Python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "d:\bits\devops\random\flask_app\src\unittest\python\homepage_tests.py", line 37, in test_convert_epoch_to_datetime_valid
    self.assertTrue(html_result.startswith('<html>'))
  File "C:\Python39\lib\unittest\case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
]]></failure>
	</testcase>
</testsuite>
