<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="homepage_tests.TestConvertEpochToDatetime-20240310230623" tests="4" file="homepage_tests.py" time="0.011" timestamp="2024-03-10T23:06:23" failures="1" errors="0" skipped="0">
	<testcase classname="homepage_tests.TestConvertEpochToDatetime" name="test_convert_epoch_to_datetime_negative" time="0.003" timestamp="2024-03-10T23:06:23"/>
	<testcase classname="homepage_tests.TestConvertEpochToDatetime" name="test_convert_epoch_to_datetime_valid" time="0.002" timestamp="2024-03-10T23:06:23"/>
	<testcase classname="homepage_tests.TestConvertEpochToDatetime" name="test_convert_epoch_to_datetime_zero" time="0.001" timestamp="2024-03-10T23:06:23"/>
	<testcase classname="homepage_tests.TestConvertEpochToDatetime" name="test_convert_epoch_to_datetime_none" time="0.005" timestamp="2024-03-10T23:06:23">
		<failure type="AssertionError" message="'Error: Epoch time parameter is required.' not found in ('&lt;h1&gt;Error: Epoch time parameter is required.&lt;/h1&gt;', 400)"><![CDATA[Traceback (most recent call last):
  File "C:\Python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python39\lib\unittest\case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "C:\Python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "d:\bits\devops\random\flask_app\src\unittest\python\homepage_tests.py", line 30, in test_convert_epoch_to_datetime_none
    self.assertIn('Error: Epoch time parameter is required.', html_result)
  File "C:\Python39\lib\unittest\case.py", line 1098, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Python39\lib\unittest\case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: 'Error: Epoch time parameter is required.' not found in ('<h1>Error: Epoch time parameter is required.</h1>', 400)
]]></failure>
	</testcase>
</testsuite>
